
//import com.mysql.jdbc.Connection;
//import com.mysql.jdbc.Statement;
//import java.sql.Connection;
//import java.sql.Statement;
//import java.sql.SQLException;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Siddhi
 */
public class register1 extends javax.swing.JFrame {

    /**
     * Creates new form register1
     */
    public register1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        mnumber = new javax.swing.JTextField();
        emailf = new javax.swing.JTextField();
        userf = new javax.swing.JTextField();
        passf = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressf = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 204, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("If you are Already registered then click here to login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Full Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mobile Number:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Username:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Email-ID:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        fname.setBackground(new java.awt.Color(255, 204, 255));
        fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnameFocusLost(evt);
            }
        });
        fname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fnameMouseExited(evt);
            }
        });
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 294, 32));

        mnumber.setBackground(new java.awt.Color(255, 204, 255));
        mnumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mnumberFocusLost(evt);
            }
        });
        mnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnumberActionPerformed(evt);
            }
        });
        jPanel1.add(mnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 272, 32));

        emailf.setBackground(new java.awt.Color(255, 204, 255));
        emailf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailfFocusLost(evt);
            }
        });
        emailf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailfMouseClicked(evt);
            }
        });
        emailf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfActionPerformed(evt);
            }
        });
        jPanel1.add(emailf, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 340, 272, 40));

        userf.setBackground(new java.awt.Color(255, 204, 255));
        userf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfActionPerformed(evt);
            }
        });
        jPanel1.add(userf, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 272, 34));

        passf.setBackground(new java.awt.Color(255, 204, 255));
        passf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passfFocusLost(evt);
            }
        });
        passf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passfMouseClicked(evt);
            }
        });
        passf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passfActionPerformed(evt);
            }
        });
        jPanel1.add(passf, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 450, 272, 35));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Address:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, -1, -1));

        addressf.setBackground(new java.awt.Color(255, 204, 255));
        addressf.setColumns(20);
        addressf.setRows(5);
        jScrollPane1.setViewportView(addressf);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 294, 60));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ODMS ICON/register.png"))); // NOI18N
        jButton3.setText("Register");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, 170, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ODMS ICON/registerfinal.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 1470, 640));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ODMS ICON/Logout.png"))); // NOI18N
        jButton5.setText("Back ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfActionPerformed

    }//GEN-LAST:event_userfActionPerformed

    private void emailfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfActionPerformed
      
    }//GEN-LAST:event_emailfActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String user=fname.getText();   
       String pwrd=passf.getText(); 
       String mobile=mnumber.getText();
 if(user.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Entered Value is the name field");
        }
  if(mobile.equals("")||mobile.length()!=10)
        {
            JOptionPane.showMessageDialog(rootPane, "Please Enter valid mobile number");
            mnumber.setText("");
        }
 else{
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String sql="INSERT INTO reg VALUES(?,?,?,?,?,?)";
            java.sql.Connection con=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/organdata","root","Siddhi@123");
            PreparedStatement pstmt=con.prepareStatement(sql);
            pstmt.setString(1,fname.getText());
            pstmt.setString(2, addressf.getText());
            pstmt.setString(3,mnumber.getText());
            pstmt.setString(4,emailf.getText());
            pstmt.setString(5,userf.getText());
            pstmt.setString(6,passf.getText());
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Registration  Successfully");
            //con.close();
           }catch(Exception e)
                {
                     JOptionPane.showMessageDialog(null, e);
                }    
     
      }
            /*    String name=fname.getText();   
                String address=addressf.getText();
                String mobileno=mnumber.getText(); 
                String emailid=emailf.getText(); 
                String username=userf.getText();
                String password=passf.getText();
        try{
                Connection con=ConnectionProvider.getcon();
                Statement st=con.createStatement();
                st.executeUpdate("insert into reg values('"+name+",'"+address+"','"+mobileno+"','"+emailid+"','"+username+"','"+password+"')");
                JOptionPane.showMessageDialog(null, "Registered Successfully!!");
        } catch (Exception ex) {
            System.out.println("error");
        }*/
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            dispose();
            login1 h=new login1();
            h.setTitle("login page");
            h.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void fnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnameMouseExited
       
    }//GEN-LAST:event_fnameMouseExited

    private void fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusLost
         String user=fname.getText();
                       int l=user.length();
                       if(user.equals(""))
                       {
                           JOptionPane.showMessageDialog(rootPane,"Enter value in the name field");
                       }
                       if(l<2){
                           JOptionPane.showMessageDialog(rootPane, "Enter value in the name field");
                       }
    }//GEN-LAST:event_fnameFocusLost

    private void passfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passfFocusLost
      
    }//GEN-LAST:event_passfFocusLost

    private void passfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passfMouseClicked
        String pwrd=passf.getText();
        int n=pwrd.length();
        if(n<8)
        {
            JOptionPane.showMessageDialog(rootPane, "Enter the strong password of 8 characters which may include symbols,alphabets and characters");
        }
    }//GEN-LAST:event_passfMouseClicked

    private void emailfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfFocusLost
        
    }//GEN-LAST:event_emailfFocusLost

    private void emailfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailfMouseClicked
        
    }//GEN-LAST:event_emailfMouseClicked

    private void mnumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mnumberFocusLost
        String mobile=mnumber.getText();
         if(mobile.length()==0)
         {}else if(mobile.length()!=10){
             JOptionPane.showMessageDialog(rootPane,"Please enter valid mobile no(only 10 digits)");
            mnumber.setText("");
         }else if(isValid(mobile)){}
         else{
             
         }
    }//GEN-LAST:event_mnumberFocusLost

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
        main h=new main();
        h.setTitle("home page");
        h.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void passfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressf;
    private javax.swing.JTextField emailf;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mnumber;
    private javax.swing.JPasswordField passf;
    private javax.swing.JTextField userf;
    // End of variables declaration//GEN-END:variables

    private boolean isValid(String mobile) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
